package io.jclaw.storage.sql;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.transaction.support.TransactionTemplate;

import javax.sql.DataSource;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.List;
import java.util.Objects;

/**
 * The SQL schema and its migrations.
 *
 * <p>Versioned DDL applied in order and recorded in {@code jclaw_schema}, so a database created
 * by an older build is brought forward on start and a newer database is refused rather than
 * misread. Each migration runs in one transaction. The DDL is written in the dialect H2 and
 * PostgreSQL share: identity columns, {@code TEXT}, plain indexes; nothing vendor-specific, so
 * one migration list serves the embedded and the hosted database.
 *
 * <p>One table holds every store's rows. The stores replay their rows in order and decode them
 * themselves, exactly as they do from a JSONL file, so what SQL adds here is durability under
 * concurrent writers, transactional rewrites, indexed reads by run and thread, and a database an
 * operator can back up and query, not a second data model to keep in step with the first.
 */
public final class SqlSchema {

    private static final Logger log = LoggerFactory.getLogger(SqlSchema.class);

    /** One schema version: the statements that take the database from the previous one to it. */
    public record Migration(int version, String description, List<String> statements) {
    }

    /** The migrations, in order. Append; never edit a shipped one. */
    public static final List<Migration> MIGRATIONS = List.of(
            new Migration(1, "rows table", List.of(
                    "CREATE TABLE jclaw_rows ("
                            + " seq BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,"
                            + " store VARCHAR(64) NOT NULL,"
                            + " run VARCHAR(200),"
                            + " thread VARCHAR(200),"
                            + " body TEXT NOT NULL)",
                    "CREATE INDEX jclaw_rows_store ON jclaw_rows (store, seq)",
                    "CREATE INDEX jclaw_rows_run ON jclaw_rows (store, run)",
                    "CREATE INDEX jclaw_rows_thread ON jclaw_rows (store, thread)")));

    private SqlSchema() {
    }

    /** The schema version this build expects. */
    public static int currentVersion() {
        return MIGRATIONS.get(MIGRATIONS.size() - 1).version();
    }

    /**
     * Brings the database to the current version, creating the version table on first use.
     *
     * @return the version the database was at before, 0 for a fresh database
     * @throws IllegalStateException when the database is newer than this build
     */
    public static int migrate(DataSource dataSource) {
        Objects.requireNonNull(dataSource, "dataSource");
        JdbcTemplate jdbc = new JdbcTemplate(dataSource);
        TransactionTemplate tx = new TransactionTemplate(new DataSourceTransactionManager(dataSource));

        jdbc.execute("CREATE TABLE IF NOT EXISTS jclaw_schema ("
                + " version INT PRIMARY KEY,"
                + " description VARCHAR(200) NOT NULL,"
                + " applied_at TIMESTAMP NOT NULL)");
        Integer at = jdbc.queryForObject("SELECT COALESCE(MAX(version), 0) FROM jclaw_schema", Integer.class);
        int before = at == null ? 0 : at;
        if (before > currentVersion()) {
            throw new IllegalStateException("database schema is version " + before
                    + " but this build knows up to " + currentVersion() + "; upgrade jclaw");
        }
        for (Migration migration : MIGRATIONS) {
            if (migration.version() <= before) {
                continue;
            }
            tx.executeWithoutResult(status -> {
                for (String statement : migration.statements()) {
                    jdbc.execute(statement);
                }
                jdbc.update("INSERT INTO jclaw_schema (version, description, applied_at) VALUES (?, ?, ?)",
                        migration.version(), migration.description(), Timestamp.from(Instant.now()));
            });
            log.debug("storage: applied schema migration {} ({})", migration.version(), migration.description());
        }
        return before;
    }
}
